var products =[{
    "id":0,
    "title":"-- Select Anyone --",
    "price":"",
    "description":"",
    "brand":"",
    "image":"img/Comparison/No_Image.png",
},{
    "id":1,
    "title":"CA Legend",
    "price": "$150",
    "description":"Legends are not made overnight, they take years to reach perfection, CA Sports making cricket bats since 1958. The apex of craftsmanship can be seen and experienced with CA Legend Bat. Ideally selected English willow cleft is handcrafted by seasoned and experienced makers who carve out each corner with perfection and fulfillment. 12 plus straight grains and all clear as this cricket bat does not come with a sticker or decal but a laser carving showing the see thoroughness of this ideal cricket bat. Bat's grip is sealed with CA's emblem that means it's parallel in quality. Each bat comes with a unique number lasered directly on the bat. Bat's toe is protected by Glass Protek technology to prevent its toe from weather conditions and chipping off. CA legend bat comes in a special packing that justifies its prestige.",
    "brand":"CA Sports",
    "image":"img/CA-Page/bat1.jpg",
},{
    "id":2,
    "title":"EVIN LEWIS 17",
    "price":"$170",
    "description":"Fresh looks new CA bat for those who motivate us to launch one after another with their great performances playing among CA gears. Prepared as per Evin Lewis taste, carefully planning his needs. Its' crafted from sorted 7+ grains willow.  Made for uncompromised performance maximizing players' time on crease. CA bat shaped with the fine-tuned handle grip that let you stay in performance to hit more shots effortlessly. This English willow cricket bat expertly formed edges among articulated middle will allow performers get ready to give the tough time to their rivals. Thoughtfully designed cricket bat stickers and unique complexion taking off the better feel while the toe guard express its toughness. The side barcode is for the brands' authenticity. Get the cricket bats, batting pads, cricket helmet, and thigh guards online. Adjustable bat price specified by estimating each level of players.",
    "brand":"CA Sports",
    "image":"img/CA-Page/bat2.jpg",
},{
    "id":3,
    "title":"PLUS 15000 PLAYERS EDITION",
    "price":"190",
    "description":"This magic bat named Plus 15000 PE is an all-time classic and hit cricket bat which is being made for all cricket connoisseurs out there. This bat is one of the extended versions of Plus 15000 but both the products hold their own value and specialty in their own way with a unique bunch of specifications that don't make any of the bat lesser than the other one. When it was being promoted on social media, this bat gained so much attention from its customers for being the strongest can handle bats of an era. Digging into its appearance then it is Grade one of seven-plus grains willow and it is crafted and manufactured keeping the aspect of balanced weight under consideration. Also, its grip makes it a pro-gear. This bat is endorsed by famous cricketers like Misbah-ul-Haq and Haris Sohail. The most unique feature to be mentioned as well as the presence of arch-shaped minimalistic red and silver stickers. Also, this product comes with a red-colored grip, and a reverse lock technology along with grooves makes them a perfect grip.",
    "brand":"CA Sports",
    "image":"img/CA-Page/bat3.jpg",
},{
    "id":4,
    "title":"SUPER LEAGUE RED BALL",
    "price":"$15",
    "description":" Designed to deliver superb performance and durability, CA super league cricket ball is a great option for club, practice, and school matches.",
    "brand":"CA Sports",
    "image":"img/CA-Page/ball1.jpg",
},{
    "id":5,
    "title":"SUPER LEAGUE WHITE",
    "price":"$15",
    "description":" Designed to deliver superb performance and durability, CA super league cricket ball is a great option for club, practice, and school matches.",
    "brand":"CA Sports",
    "image":"img/CA-Page/ball2.jpg",
},{
    "id":6,
    "title":"SUPER LEAGUE PINK",
    "price":"$15",
    "description":"Designed to deliver superb performance and durability, CA super league cricket ball is a great option for club, practice, and school matches.",
    "brand":"CA Sports",
    "image":"img/CA-Page/ball3.jpg",
},{
    "id":7,
    "title":"MLS Pro Ball",
    "price":"$170",
    "description":"No sporting spectacle can beat soccer fans in full voice. Celebrating the songs and chants that bring MLS stadiums to life, this adidas ball gives off grungy vibes with music poster-inspired graphics. Beneath that dynamic design, the seamless, thermally bonded construction and butyl bladder ensure predictability and longevity. A FIFA Quality Pro stamp guarantees pitch-perfect performances.",
    "brand":"Adidas",
    "image":"img/Adidas-Page/ball1.jpg",
},{
    "id":8,
    "title":"OCEAUNZ Pro Football",
    "price":"$170",
    "description":"Created for flowing soccer. The official match ball used during the early stages of the FIFA Women's World Cup™, this adidas Oceaunz pro ball stands out with graphics that reflect the importance of Australia and New Zealand's spectacular coastlines and life-sustaining lakes and waterways. Its seamless construction makes for a predictable flight and bounce. That Quality Pro stamp is FIFA's highest rating.",
    "brand":"Adidas",
    "image":"img/Adidas-Page/ball2.jpg",
},{
    "id":9,
    "title":"MLS LEAGUE NFHS BALL",
    "price":"$70",
    "description":"No sporting spectacle can beat soccer fans in full voice. Celebrating the songs and chants that bring MLS stadiums to life, this adidas ball gives off grungy vibes with music poster-inspired graphics. Behind that dynamic design, the seamless TSBE construction and butyl bladder ensure predictability and longevity. A FIFA Quality stamp guarantees it won't miss a beat on the field.",
    "brand":"Adidas",
    "image":"img/Adidas-Page/ball3.jpg",
},{
    "id":10,
    "title":"REACT TF-250 INDOOR-OUTDOOR BASKETBALL",
    "price":"$30",
    "description":"The court is a canvas and the ball is your brush. Unlock the creativity of this beautiful game with the Spalding REACT TF-250 All Surface Basketball. Spalding’s iconic grip will have you in control of your gameat all times. Whether it’s the behind-the-back pass you’ve been perfecting or the last second half court heave you’ve been practicing, the REACT TF-250 is ready to ball at all times. Its all surface performance composite cover guarantees that you’re set no matter when or where the game is. The game is calling. Answer the call with the Spalding REACT TF-250.",
    "brand":"Spalding",
    "image":"img/Spalding-Page/ball1.jpg",
},{
    "id":11,
    "title":"ROOKIE GEAR SOFT GRIP YOUTH BASKETBALL",
    "price":"$20",
    "description":"Made with a lighter weight than standard youth basketballs, The Spalding Rookie Gear® SGT Youth Basketball helps kids build up their skills. The sponge rubber cover gives it a soft feel, and pebble graphics help with grip.",
    "brand":"Spalding",
    "image":"img/Spalding-Page/ball2.jpg",
},{
    "id":12,
    "title":"LAYUP MINI RUBBER OUTDOOR BASKETBALL",
    "price":"$17",
    "description":"The Spalding Mini Rubber Outdoor basketball is made for pint-sized ballers or arcade-style games. It has the look and feel of a regular outdoor ball, but is sized to fit hoops with a 12-inch inside diameter.",
    "brand":"Spalding",
    "image":"img/Spalding-Page/ball3.jpg",
}
]